package filrouge.admin.bean;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commandes generated by hbm2java
 */
@Entity
@Table(name = "commandes")
public class Commandes implements java.io.Serializable {

	private Integer idcommande;
	private Date dateachat;
	private String jeuachete;

	public Commandes() {
	}

	public Commandes(Date dateachat, String jeuachete) {
		this.dateachat = dateachat;
		this.jeuachete = jeuachete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcommande", unique = true, nullable = false)
	public Integer getIdcommande() {
		return this.idcommande;
	}

	public void setIdcommande(Integer idcommande) {
		this.idcommande = idcommande;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateachat", nullable = false, length = 10)
	public Date getDateachat() {
		return this.dateachat;
	}

	public void setDateachat(Date dateachat) {
		this.dateachat = dateachat;
	}

	@Column(name = "jeuachete", nullable = false, length = 50)
	public String getJeuachete() {
		return this.jeuachete;
	}

	public void setJeuachete(String jeuachete) {
		this.jeuachete = jeuachete;
	}

}
